openapi: 3.1.0
x-stoplight:
  id: 5e6m44bnx0m4p
info:
  title: LibreView Unofficial
  version: '1.0'
  summary: LibreView Unofficial API Documentation.
  description: 'This is community-driven, unofficial documentation for the LibreView API. It is not affiliated with Abbott Diabetes Care, Inc. or any of its subsidiaries.'
  contact:
    url: 'https://github.com/FokkeZB/libreview-unofficial'
    name: LibreView Unofficial API Documentation
  termsOfService: 'https://github.com/FokkeZB/libreview-unofficial#disclaimer'
  license:
    identifier: MIT
    name: MIT
servers:
  - url: 'https://libreview-proxy.onrender.com'
    description: Hosted Proxy
  - description: Local Proxy
    url: 'http://localhost:3000'
  - url: 'https://api-us.libreview.io'
    description: US
paths:
  /llu/connections:
    parameters: []
    get:
      summary: Get Connections
      tags: []
      responses:
        '200':
          description: Connections Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    x-stoplight:
                      id: 2obtt5px0urol
                  data:
                    type: array
                    x-stoplight:
                      id: 99pukhh9vrof1
                    items:
                      $ref: '#/components/schemas/Connection'
                      x-stoplight:
                        id: jdp6awxie53d7
                  ticket:
                    $ref: '#/components/schemas/Ticket'
                    x-stoplight:
                      id: xrfmattlko2uj
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
      operationId: get-connections
      description: Retrieve the connections of the user.
      requestBody:
        content: {}
  /llu/auth/login:
    post:
      summary: Log in
      operationId: post-llu-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    status: 0
                    data:
                      user:
                        id: ':censored:'
                        firstName: ':censored:'
                        lastName: ':censored:'
                        email: ':censored:'
                        country: NL
                        uiLanguage: nl-NL
                        communicationLanguage: nl-NL
                        accountType: pat
                        uom: '0'
                        dateFormat: '2'
                        timeFormat: '2'
                        emailDay:
                          - 1
                        system:
                          messages:
                            firstUsePhoenix: 1615561848
                            firstUsePhoenixReportsDataMerged: 1615561848
                            lluAnalyticsNewAccount: 1677666823
                            lluGettingStartedBanner: 1615562010
                            lluNewFeatureModal: 1677666823
                            lluOnboarding: 1615562004
                            lvWebPostRelease: 3.5.25
                        details: {}
                        twoFactor:
                          primaryMethod: ''
                          primaryValue: ''
                          secondaryMethod: ''
                          secondaryValue: ''
                        created: 1615561848
                        lastLogin: 1686814706
                        programs: {}
                        dateOfBirth: 396144000
                        practices: {}
                        devices: {}
                        consents:
                          llu:
                            policyAccept: 1684414774
                            touAccept: 1686814706
                          realWorldEvidence:
                            policyAccept: 1624365806
                            touAccept: 0
                            history:
                              - policyAccept: 1624365806
                      messages:
                        unread: 0
                      notifications:
                        unresolved: 0
                      authTicket:
                        token: ':censored:'
                        expires: 1702447789
                        duration: 15552000000
                      invitations:
                        - ':censored:'
                      trustedDeviceToken: ''
                properties:
                  status:
                    type: integer
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                          firstName:
                            type: string
                          lastName:
                            type: string
                          email:
                            type: string
                          country:
                            type: string
                          uiLanguage:
                            type: string
                          communicationLanguage:
                            type: string
                          accountType:
                            type: string
                          uom:
                            type: string
                          dateFormat:
                            type: string
                          timeFormat:
                            type: string
                          emailDay:
                            type: array
                            items:
                              type: integer
                          system:
                            type: object
                            properties:
                              messages:
                                type: object
                                properties:
                                  firstUsePhoenix:
                                    type: integer
                                  firstUsePhoenixReportsDataMerged:
                                    type: integer
                                  lluAnalyticsNewAccount:
                                    type: integer
                                  lluGettingStartedBanner:
                                    type: integer
                                  lluNewFeatureModal:
                                    type: integer
                                  lluOnboarding:
                                    type: integer
                                  lvWebPostRelease:
                                    type: string
                          details:
                            type: object
                          twoFactor:
                            type: object
                            properties:
                              primaryMethod:
                                type: string
                              primaryValue:
                                type: string
                              secondaryMethod:
                                type: string
                              secondaryValue:
                                type: string
                          created:
                            type: integer
                          lastLogin:
                            type: integer
                          programs:
                            type: object
                          dateOfBirth:
                            type: integer
                          practices:
                            type: object
                          devices:
                            type: object
                          consents:
                            type: object
                            properties:
                              llu:
                                type: object
                                properties:
                                  policyAccept:
                                    type: integer
                                  touAccept:
                                    type: integer
                              realWorldEvidence:
                                type: object
                                properties:
                                  policyAccept:
                                    type: integer
                                  touAccept:
                                    type: integer
                                  history:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        policyAccept:
                                          type: integer
                      messages:
                        type: object
                        properties:
                          unread:
                            type: integer
                      notifications:
                        type: object
                        properties:
                          unresolved:
                            type: integer
                      authTicket:
                        $ref: '#/components/schemas/Ticket'
                      invitations:
                        type: array
                        items:
                          type: string
                      trustedDeviceToken:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: al40l130x2tgq
                password:
                  type: string
                  x-stoplight:
                    id: p1h5svm2ql6wj
      security: []
      description: ''
components:
  schemas:
    Connection:
      type: object
      properties:
        id:
          type: string
        patientId:
          type: string
        country:
          type: string
        status:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        targetLow:
          type: integer
        targetHigh:
          type: integer
        uom:
          type: integer
        sensor:
          type: object
          properties:
            deviceId:
              type: string
            sn:
              type: string
            a:
              type: integer
            w:
              type: integer
            pt:
              type: integer
            s:
              type: boolean
            lj:
              type: boolean
        alarmRules:
          type: object
          properties:
            c:
              type: boolean
            h:
              type: object
              properties:
                'on':
                  type: boolean
                th:
                  type: integer
                thmm:
                  type: number
                d:
                  type: integer
                f:
                  type: number
            f:
              type: object
              properties:
                th:
                  type: integer
                thmm:
                  type: integer
                d:
                  type: integer
                tl:
                  type: integer
                tlmm:
                  type: number
            l:
              type: object
              properties:
                'on':
                  type: boolean
                th:
                  type: integer
                thmm:
                  type: number
                d:
                  type: integer
                tl:
                  type: integer
                tlmm:
                  type: number
            nd:
              type: object
              properties:
                'on':
                  type: boolean
                i:
                  type: integer
                r:
                  type: integer
                l:
                  type: integer
            p:
              type: integer
            r:
              type: integer
            std:
              type: object
              properties: {}
        glucoseMeasurement:
          type: object
          properties:
            FactoryTimestamp:
              type: string
            Timestamp:
              type: string
            type:
              type: integer
            ValueInMgPerDl:
              type: integer
            TrendArrow:
              type: integer
            TrendMessage:
              type: 'null'
            MeasurementColor:
              type: integer
            GlucoseUnits:
              type: integer
            Value:
              type: number
            isHigh:
              type: boolean
            isLow:
              type: boolean
        glucoseItem:
          type: object
          properties:
            FactoryTimestamp:
              type: string
            Timestamp:
              type: string
            type:
              type: integer
            ValueInMgPerDl:
              type: integer
            TrendArrow:
              type: integer
            TrendMessage:
              type: 'null'
            MeasurementColor:
              type: integer
            GlucoseUnits:
              type: integer
            Value:
              type: number
            isHigh:
              type: boolean
            isLow:
              type: boolean
        glucoseAlarm:
          type: 'null'
        patientDevice:
          type: object
          properties:
            did:
              type: string
            dtid:
              type: integer
            v:
              type: string
            l:
              type: boolean
            ll:
              type: integer
            h:
              type: boolean
            hl:
              type: integer
            u:
              type: integer
            fixedLowAlarmValues:
              type: object
              properties:
                mgdl:
                  type: integer
                mmoll:
                  type: number
            alarms:
              type: boolean
            fixedLowThreshold:
              type: integer
        created:
          type: integer
      x-examples:
        Example 1:
          id: ':censored:'
          patientId: ':censored:'
          country: NL
          status: 2
          firstName: ':censored:'
          lastName: ':censored:'
          targetLow: 70
          targetHigh: 180
          uom: 0
          sensor:
            deviceId: ''
            sn: ':censored:'
            a: 1686161859
            w: 60
            pt: 4
            s: false
            lj: false
          alarmRules:
            c: true
            h:
              'on': true
              th: 250
              thmm: 13.9
              d: 1440
              f: 0.1
            f:
              th: 55
              thmm: 3
              d: 30
              tl: 10
              tlmm: 0.6
            l:
              'on': true
              th: 70
              thmm: 3.9
              d: 1440
              tl: 10
              tlmm: 0.6
            nd:
              'on': true
              i: 20
              r: 5
              l: 6
            p: 5
            r: 5
            std: {}
          glucoseMeasurement:
            FactoryTimestamp: '6/15/2023 7:37:22 AM'
            Timestamp: '6/15/2023 9:37:22 AM'
            type: 1
            ValueInMgPerDl: 278
            TrendArrow: 4
            TrendMessage: null
            MeasurementColor: 3
            GlucoseUnits: 0
            Value: 15.4
            isHigh: false
            isLow: false
          glucoseItem:
            FactoryTimestamp: '6/15/2023 7:37:22 AM'
            Timestamp: '6/15/2023 9:37:22 AM'
            type: 1
            ValueInMgPerDl: 278
            TrendArrow: 4
            TrendMessage: null
            MeasurementColor: 3
            GlucoseUnits: 0
            Value: 15.4
            isHigh: false
            isLow: false
          glucoseAlarm: null
          patientDevice:
            did: ':censored:'
            dtid: 40068
            v: 3.4.0.7368
            l: true
            ll: 70
            h: true
            hl: 250
            u: 1685217954
            fixedLowAlarmValues:
              mgdl: 60
              mmoll: 3.3
            alarms: false
            fixedLowThreshold: 0
          created: 1615562007
    Ticket:
      type: object
      properties:
        token:
          type: string
        expires:
          type: integer
        duration:
          type: integer
      x-examples:
        Example 1:
          token: ':censored:'
          expires: 1702366706
          duration: 15552000000
      examples:
        - token: 37e1b710-23ef-4aa2-b965-86fefab3e467
          expires: 1702366706
          duration: 15552000000
  securitySchemes:
    Token:
      type: http
      scheme: bearer
      description: ''
security:
  - Token: []
